// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSCVJTy5jOhnT6oRJpaJxW5whGIV7QyU',
    appId: '1:842720557413:web:ad453c4511c728b5fb498c',
    messagingSenderId: '842720557413',
    projectId: 'couture-3bec6',
    authDomain: 'couture-3bec6.firebaseapp.com',
    storageBucket: 'couture-3bec6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqVtVqrURbX91JQNF08Pyb3Z-84KcZNI',
    appId: '1:842720557413:android:1d3074d684e95b54fb498c',
    messagingSenderId: '842720557413',
    projectId: 'couture-3bec6',
    storageBucket: 'couture-3bec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjTfRYj6wa6wwS56UlbwHQHjtGMqpYAGI',
    appId: '1:842720557413:ios:87237d98d9eacbd9fb498c',
    messagingSenderId: '842720557413',
    projectId: 'couture-3bec6',
    storageBucket: 'couture-3bec6.appspot.com',
    iosBundleId: 'com.example.coutureapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjTfRYj6wa6wwS56UlbwHQHjtGMqpYAGI',
    appId: '1:842720557413:ios:87237d98d9eacbd9fb498c',
    messagingSenderId: '842720557413',
    projectId: 'couture-3bec6',
    storageBucket: 'couture-3bec6.appspot.com',
    iosBundleId: 'com.example.coutureapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJSCVJTy5jOhnT6oRJpaJxW5whGIV7QyU',
    appId: '1:842720557413:web:f6d2cff723fab540fb498c',
    messagingSenderId: '842720557413',
    projectId: 'couture-3bec6',
    authDomain: 'couture-3bec6.firebaseapp.com',
    storageBucket: 'couture-3bec6.appspot.com',
  );
}
